<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PRHistorico', 'doctrine');

/**
 * BasePRHistorico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $factura_id
 * @property integer $estado
 * @property timestamp $created_at
 * @property TEstadoFactura $TEstadoFactura
 * @property PRFactura $PRFactura
 * 
 * @method integer        getFacturaId()      Returns the current record's "factura_id" value
 * @method integer        getEstado()         Returns the current record's "estado" value
 * @method timestamp      getCreatedAt()      Returns the current record's "created_at" value
 * @method TEstadoFactura getTEstadoFactura() Returns the current record's "TEstadoFactura" value
 * @method PRFactura      getPRFactura()      Returns the current record's "PRFactura" value
 * @method PRHistorico    setFacturaId()      Sets the current record's "factura_id" value
 * @method PRHistorico    setEstado()         Sets the current record's "estado" value
 * @method PRHistorico    setCreatedAt()      Sets the current record's "created_at" value
 * @method PRHistorico    setTEstadoFactura() Sets the current record's "TEstadoFactura" value
 * @method PRHistorico    setPRFactura()      Sets the current record's "PRFactura" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePRHistorico extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_historico');
        $this->hasColumn('factura_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('estado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TEstadoFactura', array(
             'local' => 'estado',
             'foreign' => 'id'));

        $this->hasOne('PRFactura', array(
             'local' => 'factura_id',
             'foreign' => 'id'));
    }
}