<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PREmpleado', 'doctrine');

/**
 * BasePREmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property string $apellidos
 * @property string $email
 * @property integer $perfil
 * @property TRol $TRol
 * @property Doctrine_Collection $PROferta
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $PRProyecto
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getApellidos()   Returns the current record's "apellidos" value
 * @method string              getEmail()       Returns the current record's "email" value
 * @method integer             getPerfil()      Returns the current record's "perfil" value
 * @method TRol                getTRol()        Returns the current record's "TRol" value
 * @method Doctrine_Collection getPROferta()    Returns the current record's "PROferta" collection
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getPRProyecto()  Returns the current record's "PRProyecto" collection
 * @method PREmpleado          setId()          Sets the current record's "id" value
 * @method PREmpleado          setUserId()      Sets the current record's "user_id" value
 * @method PREmpleado          setName()        Sets the current record's "name" value
 * @method PREmpleado          setApellidos()   Sets the current record's "apellidos" value
 * @method PREmpleado          setEmail()       Sets the current record's "email" value
 * @method PREmpleado          setPerfil()      Sets the current record's "perfil" value
 * @method PREmpleado          setTRol()        Sets the current record's "TRol" value
 * @method PREmpleado          setPROferta()    Sets the current record's "PROferta" collection
 * @method PREmpleado          setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method PREmpleado          setPRProyecto()  Sets the current record's "PRProyecto" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePREmpleado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_empleado');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('apellidos', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('perfil', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TRol', array(
             'local' => 'perfil',
             'foreign' => 'id'));

        $this->hasMany('PROferta', array(
             'local' => 'id',
             'foreign' => 'creador_id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('PRProyecto', array(
             'local' => 'id',
             'foreign' => 'responsable_id'));
    }
}