<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PRCategoria', 'doctrine');

/**
 * BasePRCategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $coste_anual
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method string      getName()        Returns the current record's "name" value
 * @method integer     getCosteAnual()  Returns the current record's "coste_anual" value
 * @method PRCategoria setId()          Sets the current record's "id" value
 * @method PRCategoria setName()        Sets the current record's "name" value
 * @method PRCategoria setCosteAnual()  Sets the current record's "coste_anual" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePRCategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_categoria');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('coste_anual', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}