<?php

/**
 * BasePRFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $estado
 * @property integer $proyecto_id
 * @property integer $importe
 * @property string $codigo
 * @property string $fichero
 * @property PRProyecto $PRProyecto
 * @property Doctrine_Collection $PRHistorico
 * @property TEstadoFactura $TEstadoFactura
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method integer             getEstado()         Returns the current record's "estado" value
 * @method integer             getProyectoId()     Returns the current record's "proyecto_id" value
 * @method integer             getImporte()        Returns the current record's "importe" value
 * @method string              getCodigo()         Returns the current record's "codigo" value
 * @method string              getFichero()        Returns the current record's "fichero" value
 * @method PRProyecto          getPRProyecto()     Returns the current record's "PRProyecto" value
 * @method Doctrine_Collection getPRHistorico()    Returns the current record's "PRHistorico" collection
 * @method TEstadoFactura      getTEstadoFactura() Returns the current record's "TEstadoFactura" value
 * @method PRFactura           setName()           Sets the current record's "name" value
 * @method PRFactura           setEstado()         Sets the current record's "estado" value
 * @method PRFactura           setProyectoId()     Sets the current record's "proyecto_id" value
 * @method PRFactura           setImporte()        Sets the current record's "importe" value
 * @method PRFactura           setCodigo()         Sets the current record's "codigo" value
 * @method PRFactura           setFichero()        Sets the current record's "fichero" value
 * @method PRFactura           setPRProyecto()     Sets the current record's "PRProyecto" value
 * @method PRFactura           setPRHistorico()    Sets the current record's "PRHistorico" collection
 * @method PRFactura           setTEstadoFactura() Sets the current record's "TEstadoFactura" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePRFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_factura');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('estado', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('proyecto_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('importe', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('fichero', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PRProyecto', array(
             'local' => 'proyecto_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('PRHistorico', array(
             'local' => 'id',
             'foreign' => 'factura_id'));

        $this->hasOne('TEstadoFactura', array(
             'local' => 'estado',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}