<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TEstadoFactura', 'doctrine');

/**
 * BaseTEstadoFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $PRHistorico
 * @property Doctrine_Collection $PRFactura
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method Doctrine_Collection getPRHistorico() Returns the current record's "PRHistorico" collection
 * @method Doctrine_Collection getPRFactura()   Returns the current record's "PRFactura" collection
 * @method TEstadoFactura      setId()          Sets the current record's "id" value
 * @method TEstadoFactura      setName()        Sets the current record's "name" value
 * @method TEstadoFactura      setPRHistorico() Sets the current record's "PRHistorico" collection
 * @method TEstadoFactura      setPRFactura()   Sets the current record's "PRFactura" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTEstadoFactura extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_estado_factura');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PRHistorico', array(
             'local' => 'id',
             'foreign' => 'estado'));

        $this->hasMany('PRFactura', array(
             'local' => 'id',
             'foreign' => 'estado'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}