<?php

/**
 * BasePRHito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $porcentaje
 * @property integer $momento
 * @property integer $oferta_id
 * @property PROferta $PROferta
 * 
 * @method integer  getPorcentaje() Returns the current record's "porcentaje" value
 * @method integer  getMomento()    Returns the current record's "momento" value
 * @method integer  getOfertaId()   Returns the current record's "oferta_id" value
 * @method PROferta getPROferta()   Returns the current record's "PROferta" value
 * @method PRHito   setPorcentaje() Sets the current record's "porcentaje" value
 * @method PRHito   setMomento()    Sets the current record's "momento" value
 * @method PRHito   setOfertaId()   Sets the current record's "oferta_id" value
 * @method PRHito   setPROferta()   Sets the current record's "PROferta" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePRHito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_hito');
        $this->hasColumn('porcentaje', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('momento', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('oferta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PROferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}