<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PRCoste', 'doctrine');

/**
 * BasePRCoste
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $oferta_id
 * @property integer $tipo_gasto
 * @property string $concepto
 * @property integer $dedicacion
 * @property float $importe
 * @property integer $coste_anual
 * @property TGasto $TGasto
 * @property Doctrine_Collection $PROferta
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getOfertaId()    Returns the current record's "oferta_id" value
 * @method integer             getTipoGasto()   Returns the current record's "tipo_gasto" value
 * @method string              getConcepto()    Returns the current record's "concepto" value
 * @method integer             getDedicacion()  Returns the current record's "dedicacion" value
 * @method float               getImporte()     Returns the current record's "importe" value
 * @method integer             getCosteAnual()  Returns the current record's "coste_anual" value
 * @method TGasto              getTGasto()      Returns the current record's "TGasto" value
 * @method Doctrine_Collection getPROferta()    Returns the current record's "PROferta" collection
 * @method PRCoste             setId()          Sets the current record's "id" value
 * @method PRCoste             setOfertaId()    Sets the current record's "oferta_id" value
 * @method PRCoste             setTipoGasto()   Sets the current record's "tipo_gasto" value
 * @method PRCoste             setConcepto()    Sets the current record's "concepto" value
 * @method PRCoste             setDedicacion()  Sets the current record's "dedicacion" value
 * @method PRCoste             setImporte()     Sets the current record's "importe" value
 * @method PRCoste             setCosteAnual()  Sets the current record's "coste_anual" value
 * @method PRCoste             setTGasto()      Sets the current record's "TGasto" value
 * @method PRCoste             setPROferta()    Sets the current record's "PROferta" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePRCoste extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_coste');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('oferta_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('tipo_gasto', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('concepto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('dedicacion', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'default' => '100',
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('importe', 'float', 9, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 9,
             'scale' => '2',
             ));
        $this->hasColumn('coste_anual', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TGasto', array(
             'local' => 'tipo_gasto',
             'foreign' => 'id'));

        $this->hasMany('PROferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id'));
    }
}