<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TRol', 'doctrine');

/**
 * BaseTRol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $PREmpleado
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getPREmpleado() Returns the current record's "PREmpleado" collection
 * @method TRol                setId()         Sets the current record's "id" value
 * @method TRol                setName()       Sets the current record's "name" value
 * @method TRol                setPREmpleado() Sets the current record's "PREmpleado" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTRol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_rol');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PREmpleado', array(
             'local' => 'id',
             'foreign' => 'perfil'));
    }
}