<?php

/**
 * BasePRProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $pedido
 * @property integer $cliente_id
 * @property float $importe_contratacion
 * @property string $forma_pago
 * @property string $tipo_facturacion
 * @property integer $duracion
 * @property integer $oferta_id
 * @property integer $responsable_id
 * @property PROferta $PROferta
 * @property PREmpleado $PREmpleado
 * @property PRCliente $PRCliente
 * @property Doctrine_Collection $PRFactura
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getPedido()               Returns the current record's "pedido" value
 * @method integer             getClienteId()            Returns the current record's "cliente_id" value
 * @method float               getImporteContratacion()  Returns the current record's "importe_contratacion" value
 * @method string              getFormaPago()            Returns the current record's "forma_pago" value
 * @method string              getTipoFacturacion()      Returns the current record's "tipo_facturacion" value
 * @method integer             getDuracion()             Returns the current record's "duracion" value
 * @method integer             getOfertaId()             Returns the current record's "oferta_id" value
 * @method integer             getResponsableId()        Returns the current record's "responsable_id" value
 * @method PROferta            getPROferta()             Returns the current record's "PROferta" value
 * @method PREmpleado          getPREmpleado()           Returns the current record's "PREmpleado" value
 * @method PRCliente           getPRCliente()            Returns the current record's "PRCliente" value
 * @method Doctrine_Collection getPRFactura()            Returns the current record's "PRFactura" collection
 * @method PRProyecto          setName()                 Sets the current record's "name" value
 * @method PRProyecto          setPedido()               Sets the current record's "pedido" value
 * @method PRProyecto          setClienteId()            Sets the current record's "cliente_id" value
 * @method PRProyecto          setImporteContratacion()  Sets the current record's "importe_contratacion" value
 * @method PRProyecto          setFormaPago()            Sets the current record's "forma_pago" value
 * @method PRProyecto          setTipoFacturacion()      Sets the current record's "tipo_facturacion" value
 * @method PRProyecto          setDuracion()             Sets the current record's "duracion" value
 * @method PRProyecto          setOfertaId()             Sets the current record's "oferta_id" value
 * @method PRProyecto          setResponsableId()        Sets the current record's "responsable_id" value
 * @method PRProyecto          setPROferta()             Sets the current record's "PROferta" value
 * @method PRProyecto          setPREmpleado()           Sets the current record's "PREmpleado" value
 * @method PRProyecto          setPRCliente()            Sets the current record's "PRCliente" value
 * @method PRProyecto          setPRFactura()            Sets the current record's "PRFactura" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePRProyecto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_proyecto');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('pedido', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cliente_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('importe_contratacion', 'float', 9, array(
             'type' => 'float',
             'notnull' => true,
             'length' => 9,
             'scale' => '2',
             ));
        $this->hasColumn('forma_pago', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tipo_facturacion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('duracion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('oferta_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('responsable_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PROferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id'));

        $this->hasOne('PREmpleado', array(
             'local' => 'responsable_id',
             'foreign' => 'id'));

        $this->hasOne('PRCliente', array(
             'local' => 'cliente_id',
             'foreign' => 'id'));

        $this->hasMany('PRFactura', array(
             'local' => 'id',
             'foreign' => 'proyecto_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}