<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TEstado', 'doctrine');

/**
 * BaseTEstado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $PROferta
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getPROferta() Returns the current record's "PROferta" collection
 * @method TEstado             setId()       Sets the current record's "id" value
 * @method TEstado             setName()     Sets the current record's "name" value
 * @method TEstado             setPROferta() Sets the current record's "PROferta" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTEstado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_estado');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PROferta', array(
             'local' => 'id',
             'foreign' => 'estado'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}