<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PRLog', 'doctrine');

/**
 * BasePRLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $oferta_id
 * @property integer $estado
 * @property timestamp $fecha_cambio
 * @property TEstado $TEstado
 * @property PROferta $PROferta
 * @property PREmpleado $PREmpleado
 * 
 * @method integer    getUsuarioId()    Returns the current record's "usuario_id" value
 * @method integer    getOfertaId()     Returns the current record's "oferta_id" value
 * @method integer    getEstado()       Returns the current record's "estado" value
 * @method timestamp  getFechaCambio()  Returns the current record's "fecha_cambio" value
 * @method TEstado    getTEstado()      Returns the current record's "TEstado" value
 * @method PROferta   getPROferta()     Returns the current record's "PROferta" value
 * @method PREmpleado getPREmpleado()   Returns the current record's "PREmpleado" value
 * @method PRLog      setUsuarioId()    Sets the current record's "usuario_id" value
 * @method PRLog      setOfertaId()     Sets the current record's "oferta_id" value
 * @method PRLog      setEstado()       Sets the current record's "estado" value
 * @method PRLog      setFechaCambio()  Sets the current record's "fecha_cambio" value
 * @method PRLog      setTEstado()      Sets the current record's "TEstado" value
 * @method PRLog      setPROferta()     Sets the current record's "PROferta" value
 * @method PRLog      setPREmpleado()   Sets the current record's "PREmpleado" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePRLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_r_log');
        $this->hasColumn('usuario_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('oferta_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('estado', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('fecha_cambio', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TEstado', array(
             'local' => 'estado',
             'foreign' => 'id'));

        $this->hasOne('PROferta', array(
             'local' => 'oferta_id',
             'foreign' => 'id'));

        $this->hasOne('PREmpleado', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));
    }
}