pr_factura:
  class: sfDoctrineRouteCollection
  options:
    model:                PRFactura
    module:               factura
    prefix_path:          /factura
    column:               id
    with_wildcard_routes: true

pr_proyecto:
  class: sfDoctrineRouteCollection
  options:
    model:                PRProyecto
    module:               proyecto
    prefix_path:          /proyecto
    column:               id
    with_wildcard_routes: true

pr_categoria:
  class: sfDoctrineRouteCollection
  options:
    model:                PRCategoria
    module:               recursos
    prefix_path:          /recursos
    column:               id
    with_wildcard_routes: true

pr_empleado:
  class: sfDoctrineRouteCollection
  options:
    model:                PREmpleado
    module:               usuarios
    prefix_path:          /usuarios
    column:               id
    with_wildcard_routes: true

pr_oferta:
  class: sfDoctrineRouteCollection
  options:
    model:                PROferta
    module:               oferta
    prefix_path:          /oferta
    column:               id
    with_wildcard_routes: true

pr_cliente:
  class: sfDoctrineRouteCollection
  options:
    model:                PRCliente
    module:               cliente
    prefix_path:          /cliente
    column:               id
    with_wildcard_routes: true


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: oferta, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
