<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/06/17 10:11:24
sfConfig::add(array(
  'app_max_ofertas_on_homepage' => 5,
  'app_max_ofertas_on_estado' => 20,
  'app_max_proyectos_on_homepage' => 20,
  'app_max_facturas_on_homepage' => 5,
  'app_max_facturas_on_estado' => 20,
  'app_max_facturas_on_cliente' => 20,
  'app_max_facturas_on_mes' => 20,
  'app_wwwdomain' => 'http://192.168.1.123',
));
