<?php

/**
 * PRCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PRCliente extends BasePRCliente
{
    public function countFacturas()
    {
      return Doctrine_Core::getTable('PRFactura')->countFacturas($this->getFacturasQuery());
    }
    
    public function getFacturas($max = 10)
    {
    $q = $this->getFacturasQuery()
      ->limit($max);
    return $q->execute();
    
    }
    
    
    public function getFacturasQuery()
    {
        $q = Doctrine_Query::create()
        ->from('PRFactura o')
        ->leftJoin('o.PRProyecto p')
        ->where('p.cliente_id = ?', $this->getId());
        return Doctrine_Core::getTable('PRFactura')->addFacturasQuery($q);
    }
    
    public function sumFacturas()
    {
        $query = 'SELECT SUM(f.importe) as total, t.name as estado FROM (p_r_factura f LEFT JOIN p_r_proyecto p ON f.proyecto_id = p.id) LEFT JOIN t_estado_factura t ON t.id = f.estado WHERE p.cliente_id = '.$this->getId().' GROUP BY t.name';
        // get Doctrine_Connection object
        $conn = Doctrine_Manager::getInstance()->connection();
        // execute SQL query, receive Doctrine_Connection_Statement
        $st = $conn->execute($query);
        // fetch query result
        $result = $st->fetchAll();
      
      return $result;
    }
}
