<?php

/**
 * PREmpleado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PREmpleado extends BasePREmpleado
{
    public function puedeValidar(){
        $rol = Doctrine::getTable('TRol')->find(array($this->getPerfil()))->getName();
        return ($rol == 'Validador Técnico' || $rol == 'Validador Económico');
    }
    
    public function firmarOferta(PROferta $pr_oferta){
        $rol = Doctrine::getTable('TRol')->find(array($this->getPerfil()))->getName();
        if($rol == 'Validador Técnico'){
            $pr_oferta->setFirma1('1');
            $pr_oferta->save();
        }elseif($rol == 'Validador Económico'){
            $pr_oferta->setFirma2('1');
            $pr_oferta->save();
        }else{
            return 0;
        }
    }
    
    public function getFacturas($max = 10)
    {
    $q = $this->getFacturasQuery()
      ->limit($max);
    return $q->execute();
    
    }
    
    
    public function getFacturasQuery()
    {
        $q = Doctrine_Query::create()
        ->from('PRFactura f')
        ->orderBY('f.updated_at DESC');
        return Doctrine_Core::getTable('PRFactura')->addFacturasQuery($q);
    }

}
