<?php

/**
 * PRFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PRFactura extends BasePRFactura
{
    public function save(Doctrine_Connection $conn = null)
    {
      $conn = $conn ? $conn : $this->getTable()->getConnection();
      $conn->beginTransaction();
        try
        {
          $ret = parent::save($conn);
          $log = new PRHistorico();
          $log->setFacturaId($this->getId());
          $log->setEstado($this->getEstado());
          $log->setCreatedAt(date('Y-m-d H:m', time()));
          $log->save();
          $this->updateLuceneIndex();
          $conn->commit();
          return $ret;
        }
        catch (Exception $e)
        {
          $conn->rollBack();
          throw $e;
          }
    }
    
    public function delete(Doctrine_Connection $conn = null)
    {
      $index = PRFacturaTable::getLuceneIndex();
      foreach ($index->find('pk:'.$this->getId()) as $hit)
      {
        $index->delete($hit->id);
      }
      return parent::delete($conn);
    }

    
    public function updateLuceneIndex()
        {
          $index = PRFacturaTable::getLuceneIndex();
          // remove existing entries
          foreach ($index->find('pk:'.$this->getId()) as $hit)
          {
            $index->delete($hit->id);
          }
          $doc = new Zend_Search_Lucene_Document();
          // store job primary key to identify it in the search results
          $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));
          // index job fields
          $doc->addField(Zend_Search_Lucene_Field::UnStored('codigo',
            $this->getCodigo(), 'utf-8'));
          $doc->addField(Zend_Search_Lucene_Field::UnStored('estado',
            $this->getNombreEstado(), 'utf-8'));
          $doc->addField(Zend_Search_Lucene_Field::UnStored('concepto',
            $this->getName(), 'utf-8'));
          $doc->addField(Zend_Search_Lucene_Field::UnStored('cliente',
            $this->getProyecto()->getNombreCliente(), 'utf-8'));
          // add job to the index
          $index->addDocument($doc);
          $index->commit();
        }
        
    public function getProyecto()
    {
      return Doctrine::getTable('PRProyecto')->find(array($this->getProyectoId()));
    }
        
            
    public function getFechaEmision()
    {
        return $this->getDateTimeObject('created_at')->format('d/m/Y');
    }
    
    public function getFechaActualizacion()
    {
        return $this->getDateTimeObject('updated_at')->format('d/m/Y');
    }
    
    public function getEstados()
    {
        $q = Doctrine_Query::create()
          ->from('TEstadoFactura ef');
        return $q->execute();
    }
    
    
    public function getHistoricoCambios()
    {
      $q = Doctrine_Query::create()
          ->from('PRHistorico h')
          ->where('h.factura_id = ?', $this->getId())
          ->orderBy('h.created_at ASC');
      return $q->execute();
    }
    
    public function getNombreEstado()
    {
      return Doctrine::getTable('TEstadoFactura')->find(array($this->getEstado()))->getName();
    }
    
    public function getMails()
    {
      $mails = array('plm.price@price-roch.es'=>'Admin');
      $q = Doctrine_Query::create()
            ->from('PREmpleado e')
            ->leftJoin('e.TRol r')
            ->where('e.id = ?', $this->getProyecto()->getResponsableId())
            ->orWhere('r.name  != ?', 'Director');
      foreach($q->execute() as $c){
        $mails[$c->getEmail()] = $c->getName().' '.$c->getApellidos();
      }
      return $mails;
    }
}
