<?php

/**
 * PRHistorico
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PRHistorico extends BasePRHistorico
{
    public function getNombreEstado()
    {
      return Doctrine::getTable('TEstadoFactura')->find(array($this->getEstado()))->getName();
    }
    
    
    public function getFacturasQuery()
    {
        $q = Doctrine_Query::create()
        ->from('PRFactura f')
        ->leftJoin('f.PRHistorico h')
        ->where('MONTH(f.created_at) = ?', $this->getMonth())
        ->andWhere('YEAR(f.created_at) = ?',  $this->getYear());
        return Doctrine_Core::getTable('PRFactura')->addFacturasQuery($q);
    }
    
    public function getFacturas($max = 10)
    {
    $q = $this->getFacturasQuery()
      ->limit($max);
    return $q->execute();
    
    }
    
    public function getMonth()
    {
        return $this->getDateTimeObject('created_at')->format('m');
    }
    
    public function getYear()
    {
        return $this->getDateTimeObject('created_at')->format('Y');
    }
    
    public function countFacturas()
    {
      return Doctrine_Core::getTable('PRFactura')->countFacturas($this->getFacturasQuery());
    }
    
    public function sumFacturas()
    {
      $q = $this->getFacturasQuery();
      return Doctrine_Core::getTable('PRFactura')->sumFacturas($q);
    }
}
