<?php

/**
 * PRProyecto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PRProyecto extends BasePRProyecto
{
    public function save(Doctrine_Connection $conn = null)
    {
      $conn = $conn ? $conn : $this->getTable()->getConnection();
      $conn->beginTransaction();
        try
        {
          $ret = parent::save($conn);
          $this->updateLuceneIndex();
          $conn->commit();
          return $ret;
        }
        catch (Exception $e)
        {
          $conn->rollBack();
          throw $e;
          }
    }
    
    public function delete(Doctrine_Connection $conn = null)
    {
      $index = PRProyectoTable::getLuceneIndex();
      foreach ($index->find('pk:'.$this->getId()) as $hit)
      {
        $index->delete($hit->id);
      }
      return parent::delete($conn);
    }

    
    public function updateLuceneIndex()
        {
          $index = PRProyectoTable::getLuceneIndex();
          // remove existing entries
          foreach ($index->find('pk:'.$this->getId()) as $hit)
          {
            $index->delete($hit->id);
          }
          $doc = new Zend_Search_Lucene_Document();
          // store job primary key to identify it in the search results
          $doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));
          // index job fields
          $doc->addField(Zend_Search_Lucene_Field::UnStored('codigo',
            $this->getCodigo(), 'utf-8'));
          $doc->addField(Zend_Search_Lucene_Field::UnStored('responsable',
            $this->getResponsable(), 'utf-8'));
          $doc->addField(Zend_Search_Lucene_Field::UnStored('titulo',
            $this->getName(), 'utf-8'));
          $doc->addField(Zend_Search_Lucene_Field::UnStored('pedido',
            $this->getPedido(), 'utf-8'));
          $doc->addField(Zend_Search_Lucene_Field::UnStored('cliente',
            $this->getNombreCliente(), 'utf-8'));
          // add job to the index
          $index->addDocument($doc);
          $index->commit();
        }
    
    public function getOferta()
    {
        return Doctrine::getTable('PROferta')->find(array($this->getOfertaId()));
    }
    
    public function getFacturas()
    {
       $q = Doctrine_Query::create()
            ->from('PRFactura f')
            ->where('f.proyecto_id = ?', $this->getId());
       return $q->execute();
    }
    
    public function getNombreCliente()
    {
      return Doctrine::getTable('PRCliente')->find(array($this->getClienteId()))->getName();
    }
    
    public function getResponsable()
    {
      return Doctrine::getTable('PREmpleado')->find(array($this->getResponsableId()))->getName();
    }
    
    public function getCodigo()
    {
        return 'PR-'.$this->getDateTimeObject('created_at')->format('Y').'-'.(string)$this->getId() ;
    }
    
    public function sumFacturas()
    {
        $q = Doctrine_Query::create()
          ->where('f.proyecto_id = ?', $this->getId());
        return Doctrine_Core::getTable('PRFactura')->sumFacturas($q);
    }
}
