<?php

/**
 * TEstadoFactura
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TEstadoFactura extends BaseTEstadoFactura
{
    public function getFacturas($max = 10)
    {
    $q = $this->getFacturasQuery()
      ->limit($max);
    return $q->execute();
    
    }
    public function countFacturas()
    {
      $q = Doctrine_Query::create()
        ->from('PRFactura o')
        ->where('o.estado = ?', $this->getId());
      return Doctrine_Core::getTable('PRFactura')->countFacturas($q);
    }

    public function getFacturasQuery()
    {
        $q = Doctrine_Query::create()
          ->from('PRFactura o')
          ->where('o.estado = ?', $this->getId());
        return Doctrine_Core::getTable('PRFactura')->addFacturasQuery($q);
    }
    
    public function sumFacturas()
    {
        $q = Doctrine_Query::create()
          ->where('f.estado = ?', $this->getId());
        return Doctrine_Core::getTable('PRFactura')->sumFacturas($q);
    }
}
