<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/06/17 10:10:39

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=priceroch',
  'username' => 'root',
  'password' => 'sonrie',
  'encoding' => 'utf8',
  'name' => 'doctrine',
)),);
