<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/06/17 11:40:23
sfConfig::add(array(
  'mod_estado_factura_enabled' => true,
  'mod_estado_factura_view_class' => 'sfPHP',
));
